config:
  credentials: []
  project_repos:
    github.com/ACTRIS-Data-Centre/actris-jupyter-hub:
      branch: main
      repo: https://github.com/ACTRIS-Data-Centre/actris-jupyter-hub
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub git:
        commands:
        - /usr/bin/env sh .sqa/script.avocado_rugged_frog.sh
        container: qc.acc_walnut_brilliant_raccoon
  QC.Doc:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.porcelain_loyal_swan.sh
        container: qc.doc_mustard_dreamy_jellyfish
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub git:
        commands:
        - /usr/bin/env sh .sqa/script.periwinkle_feisty_wasp.sh
        container: qc.doc_blush_industrious_rhinoceros
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chocolate_aware_grasshopper.sh
        container: qc.doc_steel_generous_horse
  QC.Lic:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub licensee:
        commands:
        - /usr/bin/env sh .sqa/script.amaranth_tenacious_chinchilla.sh
        container: qc.lic_saffron_stubborn_chipmunk
  QC.Sec:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub bandit:
        commands:
        - /usr/bin/env sh .sqa/script.amethyst_sarcastic_impala.sh
        container: qc.sec_slate_serene_roc
  QC.Sty:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub flake8:
        commands:
        - /usr/bin/env sh .sqa/script.saffron_perky_boa.sh
        container: qc.sty_boysenberry_content_impala
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.jasmine_perceptive_walrus.sh
        container: qc.sty_wine_radiant_pelican
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.malachite_artistic_roc.sh
        container: qc.sty_aqua_organized_cougar
  QC.Uni:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub pytest:
        commands:
        - /usr/bin/env sh .sqa/script.glaucous_tranquil_eagle.sh
        container: qc.uni_teal_anxious_sloth
  QC.Ver:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.periwinkle_clever_bison.sh
        container: qc.ver_chartreuse_clever_alpaca
timeout: 5400
