config:
  credentials: []
  project_repos:
    github.com/ACTRIS-Data-Centre/actris-jupyter-hub:
      branch: main
      repo: https://github.com/ACTRIS-Data-Centre/actris-jupyter-hub
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint_fix
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub git:
        commands:
        - /usr/bin/env sh .sqa/script.magenta_sarcastic_catfish.sh
        container: qc.acc_dawn_responsible_frog
  QC.Doc:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lime_amiable_buffalo.sh
        container: qc.doc_butter_patient_ostrich
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub git:
        commands:
        - /usr/bin/env sh .sqa/script.tide_spontaneous_parrot.sh
        container: qc.doc_mint_quirky_cobra
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.glacier_authentic_gorilla.sh
        container: qc.doc_wisteria_hardworking_swan
  QC.Lic:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cardamom_imaginative_macaw.sh
        container: qc.lic_cayenne_wise_hyena
  QC.Sec:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub bandit:
        commands:
        - /usr/bin/env sh .sqa/script.eggplant_open_ferret.sh
        container: qc.sec_mauve_plucky_jellyfish
  QC.Sty:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pink_vibrant_warthog.sh
        container: qc.sty_wine_empathetic_griffin
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.silver_melancholy_panda.sh
        container: qc.sty_isabelline_amused_ostrich
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub pynblint.py:
        commands:
        - /usr/bin/env sh .sqa/script.orange_alert_hornbill.sh
        container: qc.sty_caramel_blissful_orca
  QC.Uni:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub pytest:
        commands:
        - /usr/bin/env sh .sqa/script.harlequin_wise_lobster.sh
        container: qc.uni_incarnadine_ambitious_caiman
  QC.Ver:
    repos:
      github.com/ACTRIS-Data-Centre/actris-jupyter-hub get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.green_gentle_wolf.sh
        container: qc.ver_silver_smart_hummingbird
timeout: 5400
